[upsampling]
# Number of rows in the original image.
original_rows = 3
# Number of columns in the original image.
original_cols = 3
# Number of rows in the upsampled image.
upsampled_rows = 5
# Number of columns in the upsampled image.
upsampled_cols = 5
# Index of the sample image to be generated.
# 1: One constant circle.
# 2: Two constant circles.
# 3: One quadratic circle.
# 4: One smooth circle.
# 5: Two smooth circles.
sample_image_index = 4

# Configurations of Numerical Collection C++ library.
"$schema" = "https://numcollect.musicscience37.com/config_schema/v3/config_schema.json"

[[num_collect.logging.tag_configs]]
tag = ""
output_log_level = "debug"
output_log_level_in_child_iterations = "warning"

[[num_collect.logging.tag_configs]]
tag = "num_collect::opt::gaussian_process_optimizer"
iteration_output_period = 1
